// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataValidationUsingMetaData.Models
{
    public partial class Student
    {
        [Column("ID")]
        [Key]
        public int Id { get; set; }

        [StringLength(100)]
        [Unicode(false)]
        [Required(ErrorMessage = "Name is required")]
        [Display(Name = "Student Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Address is required")]
        [StringLength(100)]
        [Display(Name = "Address")]
        [Unicode(false)]
        public string Address { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [Display(Name = "Student Email")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        [StringLength(75)]
        [Unicode(false)]
        public string Email { get; set; }

        [Required(ErrorMessage = "Class is required")]
        [StringLength(5)]
        [Display(Name = "Which Class ")]
        [Unicode(false)]
        public string Class { get; set; }
    }
}